DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('', views.index, name="article_index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('create/article/', views.create_article, name="create_article"),
    path('article/<int:id>/', views.detail, name="detail"),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('comment/<int:id>/', views.addComment, name="comment"), 
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length = 50, verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")
    article_image = models.FileField(blank=True, null=True,verbose_name="Makaleye Resim Ekle")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim Soyisim")
    comment_content = models.CharField(max_length = 250, verbose_name = "Yorumunuz")
    comment_created_date = models.DateTimeField(auto_now_add=True,verbose_name="Yorum Oluşturma Tarihi")
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ["-comment_created_date"]

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForms(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',"article_image"]

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=50,label = "Şifre", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=50,label = "Şifre Tekrar", widget=forms.PasswordInput)
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor.")
        values = {
            "username" : username,
            "password" : password
        }
        return values


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=50,label = "Şifre", widget=forms.PasswordInput)

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForms
from .models import Article, Comment
from django.contrib import messages

def index(request):
    articles = Article.objects.all().filter(author=request.user)
    return render(request,"index.html",{"articles":articles})

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    #articles = Article.object.filter(author=request.user)
    articles = Article.objects.all().filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def create_article(request):
    form = ArticleForms(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")
    return render(request,"create_article.html",{"form":form})

def detail(request,id):
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def update(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForms(request.POST or None, request.FILES or None, instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})

@login_required(login_url = "user:login")
def delete(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request, "Makale Başarıyla Silindi")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    #return redirect("/articles/article/"+str(id))
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib import messages
def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser = User(username=username)
        newUser.set_password(password)
        newUser.save()
        auth_login(request,newUser)
        messages.success(request, 'Üyelik Başarıyla Oluşturuldu.')
        return redirect("index")
    context = {
        "form":form
    }
    return render(request,"register.html",context)

def login(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username,password=password)
        if user is None:
            messages.warning(request, 'Kullanıcı adı ve şifre hatalı.')
            return render(request,"login.html",context)
        messages.success(request, 'Başarıyla Giriş Yaptınız.')
        auth_login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

def logout(request):
    auth_logout(request)
    messages.success(request, 'Başarıyla Çıkış Yaptınız.')
    return redirect("index")

templates/about.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
    <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>About</h1>
                        <span class="subheading">me</span>
                    </div>
                </div>
            </div>
        </div>
    </header> 
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
{% endblock body %}

templates/create_article.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <header class="masthead"  >
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto"> 
                </div>
            </div>
        </div>
    </header>  
    <br>
    <div class="container">
        <div class="row">
        <br><br>
            <div class="col-lg-8 col-md-10 mx-auto">
                <form method="post" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }} 
                    <button type="submit" class="btn btn-primary btn-lg">Makale Oluştur</button>
                    <a href="/articles/dashboard/" class="btn btn-danger btn-lg">Makaleler</a>
                </form>
            </div>
        </div>
    </div>                          
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <header class="masthead"  >
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto"> 
                     
                </div>
            </div>
        </div>
    </header>  
    <br>
    <div class="container">
        <div class="row">
            <a href="/articles/create/article" class="btn btn-block btn-success">Add Article</a>
            <br>
            <div class="col-lg-12 col-md-12 mx-auto">
            {% if articles %}
                <table class="table table-responsive table-hover ">
                    <tr><th>id</th><th>Başlık</th><th>Yazar</th><th>Tarih</th><th>#</th><tr>
                    {% for article in articles %}
                        <tr>
                            <td>{{article.id}}</td>
                            <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
                            <td>{{article.author}}</td>
                            <td>{{article.created_date}}</td>
                            <td>
                                <a href="/articles/update/{{article.id}}" class="btn btn-warning">Düzenle</a>
                                <a href="/articles/delete/{{article.id}}" class="btn btn-danger">Sil</a>
                            </td>
                        </tr>
                    {% endfor %}
                <table>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    Henüz Bir Makaleniz Bulunmuyor.
                </div>
            {% endif %}
            </div>
        </div>
    </div>                          
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
    {% if article %}
        {% if article.article_image %}
            <header class="masthead" style="background-image: url('{{article.article_image.url}}')">
        {% else %} 
            <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
        {% endif %}
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto"> 
                        <div class="post-heading">
                            <h1>{{article.title}}</h1>
                            <span class="meta">Posted by <a href="#">{{ article.author }}</a> on {{ article.created_date }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header> 
        <div style="text-align: justify;">{{ article.content|safe }} </div>
        <div class="card my-4">
            <h5 class="card-header">Yorum Ekle</h5>
            <div class="card-body">
                <form method="post" action="{% url 'article:comment' article.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="comment_author" class="form-control" placeholder="İsminiz" required>
                    </div>
                    <div class="form-group"> 
                        <textarea class="form-control" rows="3" style="resize:none;" name="comment_content" placeholder="Yorumunuz" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-danger">Ekle</button>
                </form>
            </div>
        </div>

        {% if comments %}
            {% for comment in comments %}
                <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="{% static 'img/user.png' %}" width="50px">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.comment_author }} / <small>{{ comment.comment_created_date }}</small></h5>
                        {{ comment.comment_content }}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-danger" role="alert">
                İlk Yorum Yapan Siz olun
            </div>
        {% endif %}
    {% else %} 
        <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto"> 
                        <div class="post-heading">
                            <div class="alert alert-danger">Yazı Bulunamadı</div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    {% endif %}
{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
  <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Anasayfa</h1>
            <span class="subheading">Django / Python</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="col-lg-8 col-md-10 mx-auto">
    {% if articles %}
      {% for article in articles %} 
          <div class="post-preview">
            <a href="{% url 'article:detail' article.id %}">
              <h2 class="post-title">{{article.title}}</h2>
              <h3 class="post-subtitle">{{article.content|striptags|truncatewords:10}}</h3>
            </a>
            <p class="post-meta">Posted by <a href="#">{{article.author}}</a> on {{article.created_date}}</p> </div>
          <hr>
      {% endfor %}  
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts →</a>
        </div>
    {% else %}
      <div class="alert alert-danger" role="alert">
        Henüz Bir Makaleniz Bulunmuyor.
      </div>
    {% endif %} 
    </div>
{% endblock body %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="tr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title %} Django Blog {% endblock title %}</title>  
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">Flask Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu<i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}" title="About Page">About</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'article:dashboard' %}" title="Admin Page">{{ request.user.username }}</a> </li>
                            <li class="nav-item active"><a class="nav-link" href="{% url 'user:logout' %}" title="Çıkış Yap">Çıkış Yap</a> </li>
                        {% else %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'user:register' %}" title="Kayıt Ol">Kayıt Ol</a> </li>
                            <li class="nav-item active"><a class="nav-link" href="{% url 'user:login' %}" title="Giriş Yap">Giriş Yap</a> </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock body %}
        
        {% if messages %} 
            {% for message in messages %} 
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                    {{ message }}
                </div>
            {% endfor %} 
        {% endif %}
        <hr><hr>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="http://github.com/senocak">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
                    </div>
                </div>
            </div>
        </footer>
        <script src="{% static 'js/jquery-3.3.1.js' %}"></script> 
        <script src="{% static 'js/clean-blog.min.js' %}"></script> 
        <!--
        <script src="{% static 'js/ckeditor.js' %}"></script> 
        <script>
            CKEDITOR.replace( 'content',{
                allowedContent : true
            });
        </script>
        -->
        <script src="{% static 'js/run_prettify.js' %}"></script> 
  </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
    <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto"> 
                    <div class="post-heading">
                        <h1>Giriş Yap</h1>
                    </div>
                </div>
            </div>
        </div>
    </header> 
    <style type="text/css">
        .signup-form {
            width: 500px;
            margin: 0 auto;
            padding: 30px 0;
        } 
    </style>
    <div class="signup-form"> 
        <form method="post" class="form-horizontal">
            {% csrf_token %}
            {{ form|crispy }} 
            <button type="submit" class="btn btn-primary btn-lg">Giriş Yap</button>
        </form>
    </div>                             
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %} 
    <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto"> 
                    <div class="post-heading">
                        <h1>Kayıt Ol</h1>
                    </div>
                </div>
            </div>
        </div>
    </header> 
    <style type="text/css">
        .signup-form {
            width: 500px;
            margin: 0 auto;
            padding: 30px 0;
        } 
    </style>
    <div class="signup-form">  
        <form method="post" class="form-horizontal">
            {% csrf_token %}
            {{ form|crispy }} 
            <button type="submit" class="btn btn-primary btn-lg">Kayıt Ol</button>
        </form>
    </div>                             
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <header class="masthead"  >
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto"> 
                </div>
            </div>
        </div>
    </header>  
    <br>
    <div class="container">
        <div class="row">
        <br><br>
            <div class="col-lg-8 col-md-10 mx-auto">
                <form method="post" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }} 
                    <button type="submit" class="btn btn-primary btn-lg">Makale Güncelle</button>
                    <a href="/articles/dashboard/" class="btn btn-danger btn-lg">Makaleler</a>
                </form>
            </div>
        </div>
    </div>                          
{% endblock body %}